### ISSUE TITLE
Resolve all TODO comments

### ISSUE THREAD

**Issue by husio** [iov-one/weave#532]
Resolve all `TODO`, `FIXME` and `BUG` comments. Either implement missing functionality or write a proper explanation of why certain functionality is not provided and what it means.

This is a huge task that requires a lot of product knowledge.

- [ ] [context_test.go](https://github.com/iov-one/weave/blob/master/context_test.go#L47) `	// TODO: test header context!`
- [ ] [architecture/NFT.md](https://github.com/iov-one/weave/blob/master/architecture/NFT.md#L28) `TODO: link to Isabella's two docs as background`
- [ ] [architecture/NFT.md](https://github.com/iov-one/weave/blob/master/architecture/NFT.md#L214) `TODO`
- [ ] [cmd/bnsd/client/tx.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/client/tx.go#L28) `			// TODO: add fees, etc...`
- [ ] [cmd/bnsd/client/client.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/client/client.go#L52) `		// TODO: make this random`
- [ ] [cmd/bnsd/client/client.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/client/client.go#L298) `	// TODO: make this async, maybe adjust return value`
- [ ] [cmd/bnsd/client/client.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/client/client.go#L322) `				// TODO: something else?`
- [ ] [cmd/bnsd/client/main_test.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/client/main_test.go#L43) `	// TODO: check out config file...`
- [ ] [cmd/bnsd/app/app.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/app/app.go#L79) `	//TODO: Possibly revisit passing the bucket later to have more control over types?`
- [ ] [cmd/bnsd/x/nft/username/msg.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/x/nft/username/msg.go#L51) `	//TODO: This is being validated on model save`
- [ ] [cmd/bnsd/x/nft/username/handler_test.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/x/nft/username/handler_test.go#L240) `//TODO: This needs to be extended with examples where we use approvals for different users`
- [ ] [cmd/bnsd/x/nft/username/handler_test.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/x/nft/username/handler_test.go#L390) `//TODO: This needs to be extended with examples where we use approvals for different users`
- [ ] [cmd/bnsd/x/nft/username/msg_test.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/x/nft/username/msg_test.go#L90) `		// TODO: Add checks for approvals`
- [ ] [cmd/bnsd/x/nft/username/msg_test.go](https://github.com/iov-one/weave/blob/master/cmd/bnsd/x/nft/username/msg_test.go#L91) `		// TODO: Add checks for TokenDetails`
- [ ] [cmd/bcpd/app/init.go](https://github.com/iov-one/weave/blob/master/cmd/bcpd/app/init.go#L79) `	// TODO: anyone can make a token????`
- [ ] [coverage/upload.sh](https://github.com/iov-one/weave/blob/master/coverage/upload.sh#L831) `  # TODO validate the yaml here`
- [ ] [errors/stacktrace.go](https://github.com/iov-one/weave/blob/master/errors/stacktrace.go#L57) `	// TODO: generalize better for other hosts?`
- [ ] [store/btree.go](https://github.com/iov-one/weave/blob/master/store/btree.go#L26) `	// TODO: reuse FreeList between multiple cache wraps....`
- [ ] [store/btree.go](https://github.com/iov-one/weave/blob/master/store/btree.go#L89) `	// TODO: reuse FreeList between multiple cache wraps....`
- [ ] [store/btree.go](https://github.com/iov-one/weave/blob/master/store/btree.go#L109) `// TODO: currently noop....leave it to the garbage collector`
- [ ] [store/btree.go](https://github.com/iov-one/weave/blob/master/store/btree.go#L275) `// TODO: add support for Combine (deleting those below)`
- [ ] [store/recorder.go](https://github.com/iov-one/weave/blob/master/store/recorder.go#L49) `// TODO: record new value???`
- [ ] [store/recorder.go](https://github.com/iov-one/weave/blob/master/store/recorder.go#L90) `// TODO: record new value???`
- [ ] [store/recorder.go](https://github.com/iov-one/weave/blob/master/store/recorder.go#L112) `	// TODO: reuse FreeList between multiple cache wraps....`
- [ ] [store/helpers.go](https://github.com/iov-one/weave/blob/master/store/helpers.go#L10) `// TODO: make this private and only expose Iterator interface????`
- [ ] [store/iavl/adapter.go](https://github.com/iov-one/weave/blob/master/store/iavl/adapter.go#L9) `// TODO: make these configurable?`
- [ ] [store/iavl/adapter.go](https://github.com/iov-one/weave/blob/master/store/iavl/adapter.go#L115) `// TODO: create batch and reader and wrap the rest in btree...`
- [ ] [examples/mycoind/app/init.go](https://github.com/iov-one/weave/blob/master/examples/mycoind/app/init.go#L96) `	return addr, "TODO: add a recovery phrase", nil`
- [ ] [abci.go](https://github.com/iov-one/weave/blob/master/abci.go#L74) `	//TODO: Implement when tendermint implements this properly`
- [ ] [coin/coins_test.go](https://github.com/iov-one/weave/blob/master/coin/coins_test.go#L23) `	// TODO: verify constructor checks well for errors`
- [ ] [coin/coins.go](https://github.com/iov-one/weave/blob/master/coin/coins.go#L18) `// TODO: deprecate in favor of `Coins.Combine()``
- [ ] [orm/index.go](https://github.com/iov-one/weave/blob/master/orm/index.go#L47) `	// TODO: index name must be [a-z_]`
- [ ] [app/helpers.go](https://github.com/iov-one/weave/blob/master/app/helpers.go#L38) `	// TODO: assert error if len > 1 ???`
- [ ] [app/helpers.go](https://github.com/iov-one/weave/blob/master/app/helpers.go#L51) `	// TODO: support all prefix searches (later even more ranges)`
- [ ] [app/helpers.go](https://github.com/iov-one/weave/blob/master/app/helpers.go#L74) `	// TODO: load normal iterator but then play it backwards?`
- [ ] [app/helpers.go](https://github.com/iov-one/weave/blob/master/app/helpers.go#L91) `// TODO: make this private and only expose Iterator interface????`
- [ ] [app/helpers.go](https://github.com/iov-one/weave/blob/master/app/helpers.go#L95) `	// TODO: add reverse field`
- [ ] [app/store.go](https://github.com/iov-one/weave/blob/master/app/store.go#L65) `// TODO: is this correct? nothing else to do really....`
- [ ] [app/store.go](https://github.com/iov-one/weave/blob/master/app/store.go#L190) `// TODO: not implemented (ABCI spec still unclear....)`
- [ ] [app/store.go](https://github.com/iov-one/weave/blob/master/app/store.go#L224) `	// TODO: support historical queries by getting old read-only`
- [ ] [app/store.go](https://github.com/iov-one/weave/blob/master/app/store.go#L236) `	// TODO: better version handling!`
- [ ] [app/store.go](https://github.com/iov-one/weave/blob/master/app/store.go#L255) `	// TODO: support proofs given this info....`
- [ ] [app/store.go](https://github.com/iov-one/weave/blob/master/app/store.go#L301) `// TODO: store the original validators somewhere`
- [ ] [app/store.go](https://github.com/iov-one/weave/blob/master/app/store.go#L304) `// TODO: investigate validators and consensusParams in response`
- [ ] [app/store.go](https://github.com/iov-one/weave/blob/master/app/store.go#L317) `// TODO: investigate response tags as of 0.11 abci`
- [ ] [app/store.go](https://github.com/iov-one/weave/blob/master/app/store.go#L330) `// TODO: investigate response tags as of 0.11 abci`
- [ ] [app/commit.go](https://github.com/iov-one/weave/blob/master/app/commit.go#L39) `// TODO: this should probably be protected by a mutex....`
- [ ] [app/router.go](https://github.com/iov-one/weave/blob/master/app/router.go#L22) `// TODO: look for better trie routers that handle patterns...`
- [ ] [store.go](https://github.com/iov-one/weave/blob/master/store.go#L144) `	// TODO: Get with proof, also historical queries`
- [ ] [store.go](https://github.com/iov-one/weave/blob/master/store.go#L156) `	// TODO: add Batch to atomic writes and efficiency`
- [ ] [docs/tutorial/init.rst](https://github.com/iov-one/weave/blob/master/docs/tutorial/init.rst#L5) `**TODO**`
- [ ] [docs/tutorial/datamodel.rst](https://github.com/iov-one/weave/blob/master/docs/tutorial/datamodel.rst#L146) `        // TODO`
- [ ] [docs/tutorial/integration.rst](https://github.com/iov-one/weave/blob/master/docs/tutorial/integration.rst#L5) `**TODO**`
- [ ] [docs/tutorial/handler.rst](https://github.com/iov-one/weave/blob/master/docs/tutorial/handler.rst#L51) `by a `Savepoint Decorator <TODO>`_,`
- [ ] [docs/tutorial/advanced.rst](https://github.com/iov-one/weave/blob/master/docs/tutorial/advanced.rst#L5) `**TODO**`
- [ ] [crypto/ed25519.go](https://github.com/iov-one/weave/blob/master/crypto/ed25519.go#L52) `// (TODO: look at sources of randomness, other than default crypto/rand)`
- [ ] [x/escrow/handler_test.go](https://github.com/iov-one/weave/blob/master/x/escrow/handler_test.go#L647) `	// TODO: add coins.Negative...`
- [ ] [x/escrow/handler_test.go](https://github.com/iov-one/weave/blob/master/x/escrow/handler_test.go#L856) `// how to do a query... TODO: abstract this??`
- [ ] [x/escrow/model.go](https://github.com/iov-one/weave/blob/master/x/escrow/model.go#L25) `	// TODO: code reuse???`
- [ ] [x/escrow/model.go](https://github.com/iov-one/weave/blob/master/x/escrow/model.go#L98) `// TODO: auto-generate sequence`
- [ ] [x/escrow/model.go](https://github.com/iov-one/weave/blob/master/x/escrow/model.go#L130) `	// TODO: add indexes`
- [ ] [x/auth.go](https://github.com/iov-one/weave/blob/master/x/auth.go#L40) `	// TODO: remove duplicates (don't sort?)`
- [ ] [x/cash/dynamicfee.go](https://github.com/iov-one/weave/blob/master/x/cash/dynamicfee.go#L13) `TODO: If a transaction succeeded, but requested a RequiredFee higher than paid`
- [ ] [x/cash/staticfee_test.go](https://github.com/iov-one/weave/blob/master/x/cash/staticfee_test.go#L33) `	return nil, errors.Wrap(errors.ErrHuman, "TODO: not implemented")`
- [ ] [x/cash/staticfee_test.go](https://github.com/iov-one/weave/blob/master/x/cash/staticfee_test.go#L37) `	return errors.Wrap(errors.ErrHuman, "TODO: not implemented")`
- [ ] [x/validators/controller.go](https://github.com/iov-one/weave/blob/master/x/validators/controller.go#L43) `		// TODO: improve this error message, so we use .New for stacktrace`
- [ ] [x/nft/approval_ops.go](https://github.com/iov-one/weave/blob/master/x/nft/approval_ops.go#L14) `//TODO: Sort errors and their codes`
- [ ] [x/nft/approval_ops.go](https://github.com/iov-one/weave/blob/master/x/nft/approval_ops.go#L15) `//TODO: Figure out what we need to do with counts for the next iteration`
- [ ] [x/nft/approval_ops.go](https://github.com/iov-one/weave/blob/master/x/nft/approval_ops.go#L47) `//TODO: Figure out whether we need wildcard approvals, might be wise to add an ApprovalOptions flag`
- [ ] [x/nft/base/handler_test.go](https://github.com/iov-one/weave/blob/master/x/nft/base/handler_test.go#L194) `				//TODO: Should we allow approved to remove their own approvals? :)`
- [ ] [x/nft/base/handler.go](https://github.com/iov-one/weave/blob/master/x/nft/base/handler.go#L12) `	//TODO: revisit`
- [ ] [x/nft/approvals.go](https://github.com/iov-one/weave/blob/master/x/nft/approvals.go#L78) `//TODO: Not sure I'm a fan of array of maps, but it makes sense`
- [ ] [x/nft/model.go](https://github.com/iov-one/weave/blob/master/x/nft/model.go#L72) `//TODO: Better name`
- [ ] [x/sigs/controller.go](https://github.com/iov-one/weave/blob/master/x/sigs/controller.go#L43) `		// TODO: separate into own function (verify one sig)`
- [ ] [x/namecoin/token.go](https://github.com/iov-one/weave/blob/master/x/namecoin/token.go#L81) `// TODO: remove??? On afterthought, this is probably never needed`
- [ ] [x/namecoin/handler_test.go](https://github.com/iov-one/weave/blob/master/x/namecoin/handler_test.go#L118) `	// TODO: add queries to verify`
- [ ] [x/namecoin/controller.go](https://github.com/iov-one/weave/blob/master/x/namecoin/controller.go#L7) `// TODO: better enforce token presence and sigfigs`
- [ ] [x/namecoin/init_test.go](https://github.com/iov-one/weave/blob/master/x/namecoin/init_test.go#L118) `			// TODO: check tokens`
- [ ] [x/namecoin/handler.go](https://github.com/iov-one/weave/blob/master/x/namecoin/handler.go#L25) `// TODO: check that permissioning???`
- [ ] [x/namecoin/wallet_test.go](https://github.com/iov-one/weave/blob/master/x/namecoin/wallet_test.go#L124) `		// TODO: not enforced in bucket, but in handler (SetName)`
- [ ] [x/utils/key_tagger_test.go](https://github.com/iov-one/weave/blob/master/x/utils/key_tagger_test.go#L100) `		// TODO: also check delete`
- [ ] [commands/server/getblock.go](https://github.com/iov-one/weave/blob/master/commands/server/getblock.go#L63) `	// TODO: doesn't work on windows!`
- [ ] [query.go](https://github.com/iov-one/weave/blob/master/query.go#L13) `	// TODO: implement`

**Acceptance criteria**
The `TODO`, `FIXME` and `BUG` comments are resolved with one of two options:

- [ ] Functionality implemented
- [ ] Documentation explaining why functionality is not implemented
