### ISSUE TITLE
Gov edge cases and questions

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#613]
## Questions
**do not resolve yet**
 current implementation is as good as we can do with current constitution. we may have to adjust this slightly later, and good to keep track of these questions, but no need to act yet.

- [ ] Who can create proposals? 
- [ ] Use electorate of proposal start date or proposal submission date (current implementation) ?
- [x] How to handle concurrent update electorate proposals? for example: add Alice, remove Bob, second one: remove Bob, add Charly. both can not succeed (with current implementation).
- [ ] Related to concurrent updates: how do we handle executor failures on tally. Currently it will fail the tally. A separate executor status may be helpful in the future

**These should be dealt with before release >>>**

## Refactorings
- [ ] Revisit and simplify table tests that require setup.
## Todos
- [ ] Add missing test scenarios 
  - https://github.com/iov-one/weave/pull/614#discussion_r282858134
  - https://github.com/iov-one/weave/pull/616#discussion_r282860903
  - https://github.com/iov-one/weave/pull/614#discussion_r282857656
- [ ] Store succeeded text resolutions in a bucket rather than current no-op. (Follow up from incompleted comment in https://github.com/iov-one/weave/pull/633)

**Comment by ethanfrey** [comment]
I moved important work to do into #669 and #670 

Much of the other tasks require a deeper refactoring of the acceptance test framework, so pulling this down to "clean up when we can" land.

**Comment by kmw101** [comment]
edge case and questions covered in other issues. closing
